export const INPUT_PLAYER_DETAILS = "INPUT_PLAYER_DETAILS";
export const ADD_WINNER = "ADD_WINNER";
export const ADD_TO_ALL_PLAYERS_AND_CLEAR_CURRENT_PLAYER =
  "ADD_TO_ALL_PLAYERS_AND_CLEAR_CURRENT_PLAYER";
export const LAST_STATE = "LAST_STATE";
